language: cpp
  
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "Updating linux"; sudo apt-get update -qq; sudo apt-get install -qq; fi

script:
  - echo "Building oellh.o..."
  - g++ -o oellh.o main.cpp
  - echo "Running oellh.o"
  - ./oellh.o

after_script:
  - echo "Style checking"
  - sudo bash ./scripts/styleCheck.sh
